package com.aes.model;
// Generated May 17, 2015 2:15:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name="course"
    ,catalog="aesdatabase"
)
public class Course  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String desc;
     private Set<Coursetaken> coursetakens = new HashSet<Coursetaken>(0);
     private Set<Presentation> presentations = new HashSet<Presentation>(0);
     private Set<Exam> exams = new HashSet<Exam>(0);

    public Course() {
    }

	
    public Course(String name, String desc) {
        this.name = name;
        this.desc = desc;
    }
    public Course(String name, String desc, Set<Coursetaken> coursetakens, Set<Presentation> presentations, Set<Exam> exams) {
       this.name = name;
       this.desc = desc;
       this.coursetakens = coursetakens;
       this.presentations = presentations;
       this.exams = exams;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="desc", nullable=false)
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Coursetaken> getCoursetakens() {
        return this.coursetakens;
    }
    
    public void setCoursetakens(Set<Coursetaken> coursetakens) {
        this.coursetakens = coursetakens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Presentation> getPresentations() {
        return this.presentations;
    }
    
    public void setPresentations(Set<Presentation> presentations) {
        this.presentations = presentations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="course")
    public Set<Exam> getExams() {
        return this.exams;
    }
    
    public void setExams(Set<Exam> exams) {
        this.exams = exams;
    }




}


