package com.aes.model;
// Generated May 17, 2015 2:15:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="aesdatabase"
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String role;
     private String name;
     private String username;
     private String password;
     private String bunit;
     private String type;
     private Set<Coursetaken> coursetakens = new HashSet<Coursetaken>(0);
     private Set<Examtaken> examtakens = new HashSet<Examtaken>(0);

    public User() {
    }

	
    public User(String role, String name, String username, String password, String bunit, String type) {
        this.role = role;
        this.name = name;
        this.username = username;
        this.password = password;
        this.bunit = bunit;
        this.type = type;
    }
    public User(String role, String name, String username, String password, String bunit, String type, Set<Coursetaken> coursetakens, Set<Examtaken> examtakens) {
       this.role = role;
       this.name = name;
       this.username = username;
       this.password = password;
       this.bunit = bunit;
       this.type = type;
       this.coursetakens = coursetakens;
       this.examtakens = examtakens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="role", nullable=false)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="username", nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="bunit", nullable=false)
    public String getBunit() {
        return this.bunit;
    }
    
    public void setBunit(String bunit) {
        this.bunit = bunit;
    }

    
    @Column(name="type", nullable=false, length=124)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Coursetaken> getCoursetakens() {
        return this.coursetakens;
    }
    
    public void setCoursetakens(Set<Coursetaken> coursetakens) {
        this.coursetakens = coursetakens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Examtaken> getExamtakens() {
        return this.examtakens;
    }
    
    public void setExamtakens(Set<Examtaken> examtakens) {
        this.examtakens = examtakens;
    }




}


